#!/bin/bash

echo Remember to source this

export ADDR=localhost:2555
export TLSCERT=/home/kbox/Documents/kstuff/go/src/github.com/KyleWS/motivationapp/TLS/fullchain.pem
export TLSKEY=/home/kbox/Documents/kstuff/go/src/github.com/KyleWS/motivationapp/TLS/privkey.pem

